### ISSUE TITLE
import-declaration-transform breaks imports in index.js files

### ISSUE THREAD

**Issue by peritus** [jurassix/refactoring-codemods#7]
Given the following minimal test case:

```
$> find directory
directory
directory/index.js
directory/subdir
directory/subdir/fileA.js
$> cat directory/index.js
import Foo from './subdir/fileA';
$> cat directory/subdir/fileA.js
const Foo = 1;

export default Foo;
```

Then I run the following command:

```
$> ./node_modules/.bin/jscodeshift \
--transform ./node_modules/refactoring-codemods/lib/transformers/import-declaration-transform.js \
test-refactor/directory/index.js test-refactor/directory/subdir/fileA.js \
--prevFilePath=/Users/filip/path/to/test-refactor/directory/subdir/fileA.js \
--nextFilePath=/Users/filip/path/to/test-refactor/
Processing 2 files...
Spawning 2 workers...
Sending 1 files to free worker...
Sending 1 files to free worker...
All done.
Results:
0 errors
1 unmodified
0 skipped
1 ok
Time elapsed: 1.613seconds
```

The resulting file change in `directory/index.js` is the following:

```diff
diff --git a/directory/index.js b/directory/index.js
index 5343b73..3c20f74 100644
--- a/directory/index.js
+++ b/directory/index.js
@@ -1 +1 @@
-import Foo from './subdir/fileA';
+import Foo from "..";
```

which is invalid.

I was expecting the result to be

```diff
diff --git a/directory/index.js b/directory/index.js
index 5343b73..3c20f74 100644
--- a/directory/index.js
+++ b/directory/index.js
@@ -1 +1 @@
-import Foo from './subdir/fileA';
+import Foo from "../otherdirectory/subdir/fileA";
```

Versions I'm using:

```
$> cat node_modules/jscodeshift/package.json|grep version
  "version": "0.3.30"
$> cat node_modules/refactoring-codemods/package.json |grep version
  "version": "0.3.2"
```

**Comment by jurassix** [comment]
@peritus Just to clarify, in your simplified example you are moving `fileA.js` and asserting that the relative paths in `index.js` referencing `fileA.js` have been updated? 

In your test I do see an issue with the command line options. Try the following:

```js
$> ./node_modules/.bin/jscodeshift \
--transform ./node_modules/refactoring-codemods/lib/transformers/import-declaration-transform.js \
test-refactor/directory/index.js test-refactor/directory/subdir/fileA.js \
--prevFilePath=/Users/filip/path/to/test-refactor/directory/subdir/fileA.js \
--nextFilePath=/Users/filip/path/to/test-refactor/otherdirectory/subdir/fileA.js
```

The main difference in the above is you need to give the absolute path to the `nextFilePath` option.

**Comment by jurassix** [comment]
To explain the results of your example:

By setting the `--nextFilePath=/Users/filip/path/to/test-refactor/` you essentially renamed the file to and *empty string* and it's located under the *test-refactor* directory. 

The index was then updated to look in his parent folder for an empty file.

We could try to be more user friendly here.

Please retest and let me know if I you continue to experience this or other issues.

**Comment by peritus** [comment]
@jurassix Thanks so much, I was hoping I was just holding it wrong.

Turns out, the shell script that I wrote contained this line:

```
  --nextFilePath=`pwd`/$REPO/$NEW_PATHx
```

where of course, `$NEW_PATHx` wasn't defined, resulting in the above behavior.

Thanks for the quick help and this awesome project.

**Comment by jurassix** [comment]
Nice. Glad I could help. I also have this library wrapped as an Atom plugin which is much easier to use.
